spring:
  application:
    name: autolycus-backend-application

server:
  port: 8888
  servlet:
    context-path: /autolycus-backend
com:
  annwyn:
    swagger:
      enable: true
      base-package: com.annwyn.autolycus.backend.core.controller
      version: 1.0.0
      title: 测试文档
      description: 测试文档1
