spring:
  devtools:
    add-properties: true
    restart:
      enabled: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/autolycus?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://192.168.88.88:3306/autolycus?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

#  redis:
#    host: localhost
#    password: 1234




management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
com:
  annwyn:
    mybatis:
      logger:
        enable: true
        print-sql-if-missing: true
    swagger:
      enable: true
      title: autolycus-backend
      version: 1.0.0
      base-package: com.annwyn.autolycus.core.controller


